version: "3.9"
services:
    devadopt-mvc:
        image: ${IMAGE_MVC_TAG}
        ports:
            - "3333:3333"
        depends_on:
            - devadopt-db
        restart: always
        networks:
            - devadopt-network
        env_file:
            .env
        environment:
            - NODE_OPTIONS=--max-old-space-size=14336
        deploy:
            resources:
                limits:
                    memory: 16G    # Limit to 16GB
                    cpus: "6.0"   # Limit to 6 CPUs

    devadopt-db:
        image: ${IMAGE_DB_TAG}
        ports:
            - "5432:5432"
        restart: always
        networks:
            - devadopt-network

networks:
    devadopt-network: