version: "3.9"
services:
    devadopt-mvc:
        image: customhaven/devadopt_mvc:159
        ports:
            - "3333:3333"
        depends_on:
            - devadopt-db
        restart: always
        networks:
            - devadopt-network
        env_file:
            .env

    devadopt-db:
        image: customhaven/devadopt-db:72
        ports:
            - "5432:5432"
        restart: always
        networks:
            - devadopt-network

networks:
    devadopt-network: