- hosts: production
  become: true
  vars:
    IMAGE_DB_TAG: "customhaven/devadopt-db:72"
    IMAGE_MVC_TAG: "customhaven/devadopt_mvc:204"
    docker_username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
    docker_password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
  tasks:
    - name: Navigate to directory containing docker-compose.yml
      ansible.builtin.shell: cd /home/ec2-user
      args:
        chdir: /home/ec2-user

    - name: Echo Docker image tags
      ansible.builtin.debug:
        msg: |
          Pulling Docker images:
          DB Image Tag: {{ IMAGE_DB_TAG }}
          MVC Image Tag: {{ IMAGE_MVC_TAG }}

    - name: Log in to Docker Registry
      ansible.builtin.shell: docker login -u {{ docker_username }} -p {{ docker_password }}
      args:
        chdir: /home/ec2-user

    - name: Pull Docker images
      ansible.builtin.shell: |
        echo "Pulling Docker image for DB..."
        docker pull {{ IMAGE_DB_TAG }} >> docker_pull.log 2>&1
        echo "Pulling Docker image for MVC..."
        docker pull {{ IMAGE_MVC_TAG }} >> docker_pull.log 2>&1
      args:
        chdir: /home/ec2-user

    - name: Display Docker pull log
      ansible.builtin.shell: cat docker_pull.log
      args:
        chdir: /home/ec2-user

    - name: Destroy docker-compose
      ansible.builtin.shell: docker-compose down
      args:
        chdir: /home/ec2-user


    - name: Run docker-compose
      ansible.builtin.shell: docker-compose up -d
      args:
        chdir: /home/ec2-user
