- hosts: production
  become: true
  tasks:
    - name: Navigate to directory containing docker-compose.yml
      shell: cd ~/
      args:
        chdir: /home/ec2-user

    - name: Pull Docker images
      shell: |
        docker pull {{ lookup('env', 'IMAGE_DB_TAG') }}
        docker pull {{ lookup('env', 'IMAGE_MVC_TAG') }}
      args:
        chdir: /home/ec2-user

    - name: Run docker-compose 
      shell: docker-compose up
      args:
        chdir: /home/ec2-user