pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials("AWS_ACCESS_KEY_ID")
        AWS_SECRET_ACCESS_KEY = credentials("AWS_SECRET_ACCESS_KEY")
        AWS_KEY_PAIR = credentials("AWS_PEM_ID")
        AWS_REGION = "eu-west-2"
        dockerHome = tool "myDocker"
		nodeHome = tool "myNodeJS"
        groovyHome = tool "groovy"
		PATH = "$dockerHome/bin:$nodeHome/bin:$groovyHome/bin:$PATH"
        REMOTE_TRIGGER_TOKEN = "remote_access_to_pipeline"  // Use the same token
    }
    stages {
        stage("Checkout") {
            steps {
                sh "pwd"
                sh "node --version"
            }
        }
        stage("Build") {
            steps {
                sh "pwd"
                echo "REACHED?!"
            }
        }
    }
    post {
		always {
			echo "I always run"
		}
		success {
			echo "I run when successful"
		}
		failure {
            script {
                withCredentials([usernamePassword(credentialsId: "e47030c6-b9aa-4279-8df1-5ebe235f9865", usernameVariable: "EMAIL_USER", passwordVariable: "EMAIL_PASS")]) {
                    emailext (
                        to: "mmuseaden@gmail.com,${EMAIL_USER}",
                        subject: "Jenkins Pipeline Failed: ${env.JOB_NAME} ${env.BUILD_NUMBER}",
                        body: "The Jenkins pipeline has failed. Please check the build logs for details: ${env.BUILD_URL}",
                        from: "Jenkins Pipeline <${EMAIL_USER}>",
                        mimeType: "text/plain"
                    )
                }
            }
            echo "I run when failed"
		}
	}
}